services:
  dbase:
    image: postgres:15
    container_name: dbasignacion
    environment:
      POSTGRES_DB: asignacion_tareas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    networks:
      - app_network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appasignacion
    depends_on:
      - dbase
    environment:
      CadenaPgs: Host=dbasignacion;Database=asignacion_tareas;Port=5432;Username=postgres;Password=newpassword
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8081:8081"

    networks:
      - app_network

networks:
  app_network:
   driver: bridge: