services:
  dbase:
    image: postgres:15
    container_name: dbasignacion
    environment:
      POSTGRES_DB: asignacion_tareas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    networks:
      - myappnetwork

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appasignacion
    depends_on:
      - dbase
    environment:
      CadenaPgs: Host=dbase;Database=asignacion_tareas;Port=5432;Username=postgres;Password=newpassword
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - myappnetwork
    ports:
      - "8080:8080"

networks:
  myappnetwork:
   driver: bridge: